const constants = {
    FETCH_SEMESTER_DATA_STARTED: 'FETCH_SEMESTER_DATA_STARTED',
    FETCH_SEMESTER_DATA_SUCCEEDED: 'FETCH_SEMESTER_DATA_SUCCEEDED',
    FETCH_SEMESTER_DATA_FAILED: 'FETCH_SEMESTER_DATA_FAILED',
    DELETE_SEMESTER_DATA_ERROR: 'DELETE_SEMESTER_DATA_ERROR'
};

export default constants;
