const constants = {
    FETCH_SEMESTER_DATA_STARTED: 'FETCH_SEMESTER_DATA_STARTED',
    FETCH_SEMESTER_DATA_SUCCEEDED: 'FETCH_SEMESTER_DATA_SUCCEEDED',
    FETCH_SEMESTER_DATA_FAILED: 'FETCH_SEMESTER_DATA_FAILED',
    DELETE_SEMESTER_DATA_ERROR: 'DELETE_SEMESTER_DATA_ERROR',

    LOGIN_STARTED: 'FETCH_USER_STARTED',
    LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    DELETE_LOGIN_ERROR: 'DELETE_LOGIN_ERROR'
};

export default constants;
