const constants = {
    FETCH_PROPOSALS_STARTED: 'FETCH_PROPOSALS_STARTED',
    FETCH_PROPOSALS_SUCCEEDED: 'FETCH_PROPOSALS_SUCCEEDED',
    FETCH_PROPOSALS_FAILED: 'FETCH_PROPOSALS_FAILED',
    DELETE_PROPOSALS_ERROR: 'DELETE_PROPOSALS_ERROR'
};

export default constants;
