export const API_BASE_URL = "http://tacapi.cape.saao.ac.za";
export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const FETCH_STAT_DATA_START = "FETCH_STAT_DATA_START"
export const FETCH_STAT_DATA_FAIL = "FETCH_STAT_DATA_FAIL"
export const FETCH_STAT_DATA_PASS = "FETCH_STAT_DATA_PASS"
export const FETCH_SELECTOR_DATA_START = "FETCH_SELECTOR_DATA_START"
export const FETCH_SELECTOR_DATA_FAIL = "FETCH_SELECTOR_DATA_FAIL"
export const FETCH_SELECTOR_DATA_PASS = "FETCH_SELECTOR_DATA_PASS"
export const PAGE_CHANGE = "PAGE_CHANGE"
export const SEMESTER_CHANGE = "SEMESTER_CHANGE"
export const PARTNER_CHANGE = "PARTNER_CHANGE"

export const ALL_PARTNER = 'All';

export const ADMINISTRATOR = 'Administrator';
export const SALT_ASTRONOMER = 'SALT Astronomer';
export const TAC_CHAIR = 'TAC Chair';
export const TAC_MEMBER = 'TAC Member';

export const VIEW_TIME_ALLOCATION_PAGE = 'VIEW_TIME_ALLOCATION_PAGE';
export const EDIT_TIME_ALLOCATION_PAGE = 'EDIT_TIME_ALLOCATION_PAGE';
