export const API_BASE_URL = "http://tacapi.cape.saao.ac.za"

export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const FETCHING_USER = "FETCHING_USER"
export const FAIL_TO_GET_USER = "FAIL_TO_GET_USER"


export const FETCH_STAT_DATA_START = "FETCH_STAT_DATA_START"
export const FETCH_STAT_DATA_FAIL = "FETCH_STAT_DATA_FAIL"
export const FETCH_STAT_DATA_PASS = "FETCH_STAT_DATA_PASS"

export const FETCH_PROPOSALS_PASS = "FETCH_PROPOSALS_PASS"
export const FETCH_PROPOSALS_FAIL = "FETCH_PROPOSALS_FAIL"
export const FETCH_PROPOSALS_START = "FETCH_PROPOSALS_START"

export const FETCH_TARGETS_PASS = "FETCH_TARGETS_PASS"
export const FETCH_TARGETS_FAIL = "FETCH_TARGETS_FAIL"
export const FETCH_TARGETS_START = "FETCH_TARGETS_START"

export const FETCH_SELECTOR_DATA_START = "FETCH_SELECTOR_DATA_START"
export const FETCH_SELECTOR_DATA_FAIL = "FETCH_SELECTOR_DATA_FAIL"
export const FETCH_SELECTOR_DATA_PASS = "FETCH_SELECTOR_DATA_PASS"

export const PAGE_CHANGE = "PAGE_CHANGE"
export const SEMESTER_CHANGE = "SEMESTER_CHANGE"
export const PARTNER_CHANGE = "PARTNER_CHANGE"

export const TIME_ALLOCATIONS_QUERY_START = "TIME_ALLOCATIONS_QUERY_START"
export const TIME_ALLOCATIONS_QUERY_FAIL = "TIME_ALLOCATIONS_QUERY_FAIL"
export const TIME_ALLOCATIONS_QUERY_PASS = "TIME_ALLOCATIONS_QUERY_PASS"
export const SUBMIT_TIME_ALLOCATIONS_START = "SUBMIT_TIME_ALLOCATIONS_START"
export const SUBMIT_TIME_ALLOCATIONS_PASS = "SUBMIT_TIME_ALLOCATIONS_PASS"
export const SUBMIT_TIME_ALLOCATIONS_FAIL = "SUBMIT_TIME_ALLOCATIONS_FAIL"
export const UPDATE_SINGLE_PROPOSAL = "UPDATE_SINGLE_PROPOSAL"
export const UPDATING_PROPOSALS = "UPDATING_PROPOSALS"

export const ALL_PARTNER = 'All';

export const ADMINISTRATOR = 'Administrator';
export const SALT_ASTRONOMER = 'SALT Astronomer';
export const TAC_CHAIR = 'TAC Chair';
export const TAC_MEMBER = 'TAC Member';

export const VIEW_TIME_ALLOCATION_PAGE = 'VIEW_TIME_ALLOCATION_PAGE';
export const EDIT_TIME_ALLOCATION_PAGE = 'EDIT_TIME_ALLOCATION_PAGE';

export const badTime = {
    color: 'black',
    background:"#FF6060"
};
export const goodTime = {
    color: 'black',
    background:"#d4fce6"
};
